// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrotsweidudflbuftwdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpyb3Rzd2VpZHVkZmxidWZ0d2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDA0MzEsImV4cCI6MjA3MTI3NjQzMX0.o-99-z0-DaZDcuDjgol5ywHADfVGr6iqSoPWqse0SIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});